name: "Install"
description: "Install"

runs:
  using: composite
  steps:
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: "https://registry.npmjs.org"

    - name: install yarn
      shell: bash
      run: npm i yarn -g

    - name: Install Dependencies
      shell: bash
      run: yarn install

    - name: Get Yarn cache path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
