name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Bump Version and Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
